name: CI/CD for AI-test - IDF4

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build and Push Docker Image
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - run: |
        docker build . -t my-image:latest
        docker tag my-image:latest ${{ secrets.DOCKER_REGISTRY }}/my-image:latest
        docker push ${{ secrets.DOCKER_REGISTRY }}/my-image:latest

    - name: Deploy with Docker Compose
      run: docker-compose -f docker-compose.yaml up -d