name: ai_generated_java_cicd_on_push
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: '11'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run unit tests
        run: mvn test
    name: Build and Test
  security_scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Scan code for security vulnerabilities
        uses: github/codeql-action/analyze@v2
  container_build:
    runs-on: ubuntu-latest
    needs: security_scan
    steps:
      - name: Set up Docker
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build Docker image
        run: |
          docker build . -t my-java-app
      - name: Push Docker image to registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push my-java-app