name: NEW1 CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run unit tests
      run: mvn test

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Deploy to Tomcat
      uses: turbo5000c/tomcat-root-war@v1
      with:
        war-file: 'target/*.war'
        tomcat-url: ${{ secrets.TOMCAT_URL }}
        username: ${{ secrets.TOMCAT_USERNAME }}
        password: ${{ secrets.TOMCAT_PASSWORD }}