name: WN8M Pipeline

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'renovate.json'
      - 'README.md'
    branches:
      - 'develop'
      - 'feat/**'
  
jobs:
  build:
    uses: turbo5000c/am-reuseable-workflow/.github/workflows/AM_WN8M_main-workflow.yml@main
    secrets: inherit